Dev
pepkit/pepr pull request #11
Opened 2018-10-09 20:20 UTC by michalstolarczyk

This contribution makes changes to the `Project` object initialization to match the overall concept (the subproject can be specified) and adds backward compatibility to the `implied/derived_columns` (`implied/derived_attributes` now)

2018-10-09 21:25 UTC, nsheff commented
wait -- why do we need a `subproject` slot on the `Project` object? I don't follow...

2018-10-10 00:13 UTC, michalstolarczyk commented
You're right, we don't need it. It was the easiest way to pass the subproject name to the `initialize()` method and that's why I did it. Fixed it in: https://github.com/pepkit/pepr/commit/5612340db613c7537b9df2de047afae5e4d5b358

2018-10-17 21:03 UTC, nsheff commented on R/loadConfig.R
> -#' Mapper of organism name to genomic assembly name
What were these assembly by organism functions written for? was this written by @vreuter ?

2018-10-17 22:23 UTC, vreuter commented on R/loadConfig.R
> -#' Mapper of organism name to genomic assembly name
I wrote something similar to this for `peppy`/`looper` but don't remember doing so for this package

2018-10-17 22:25 UTC, stolarczyk commented on R/loadConfig.R
> -#' Mapper of organism name to genomic assembly name
It wasn't me either

2018-10-25 13:37 UTC, nsheff requested changes
Please keep line length within bioc specificiations

2018-10-25 13:40 UTC, nsheff commented
Looking good @michalstolarczyk  -- are you ready to merge this (after my minor style change suggestions)?

2018-10-25 13:42 UTC, nsheff commented
Can you make sure to pass `R CMD check` on this?

2018-10-25 14:15 UTC, michalstolarczyk commented
Ok, made the changes to the code, package passes the `R CMD check`. Let's merge

2018-10-26 13:28 UTC, nsheff commented
Don't put the pkgdown site in the package repository; we host them at code.databio.org

2018-10-29 17:08 UTC, nsheff approved these changes

2018-10-29 17:08 UTC, nsheff commented on R/loadConfig.R
> +#' This function expands system paths (the non-absolute paths become absolute) and replaces the enviornment variables (e.g, \code{${HOME}}) with their vaules.
spelling check here, environment; values -- and line length. if you use an IDE that  that can wrap lines that can help

2018-11-14 22:51 UTC, merged